### PR TITLE
Fix/image upload and tests

### PR DESCRIPTION
**Pull request by vied12**
-  e2e test "can add item to top of the timeline" commented
-  Import lodash when it is needed and repair sir-trevor deps
- trying to fix the login e2e tests by fixing a size for the window

Depends on PR https://github.com/liveblog/superdesk-client/pull/14

### CODE REVIEW

**Comment by nistormihai** [comment]
the PR superdesk/superdesk-client#831 is closed, what is the alternative?

**Comment by vied12** [comment]
I made a new one with minimal updates there: https://github.com/liveblog/superdesk-client/pull/14

**Comment by nistormihai** [comment]
LGTM

**Comment by vladnicoara** [comment]
LGTM

**Comment by vied12** [comment]
Ok so I will merge in on the new superdesk/liveblog repository

**Comment by vied12** [comment]
merged here https://github.com/superdesk/liveblog/commit/f95b8d3d69ef056841a45c10fad14777c479bd4f

**Pull request closed without merging**
